from enum import StrEnum


class EXPMessageType(StrEnum):
    HELLO = "HELLO"
    HELLO_ACK = "HELLO_ACK"
    HEARTBEAT = "HEARTBEAT"
    ROLE_ASSIGN = "ROLE_ASSIGN"
    ROLE_ACK = "ROLE_ACK"
    ROLE_CHANGE = "ROLE_CHANGE"
    ELECTION_PROPOSE = "ELECTION_PROPOSE"
    ELECTION_VOTE = "ELECTION_VOTE"
    TASK_SUBMIT = "TASK_SUBMIT"
    TASK_DISPATCH = "TASK_DISPATCH"
    TASK_RESULT = "TASK_RESULT"
    TASK_RETRY = "TASK_RETRY"
    TASK_CANCEL = "TASK_CANCEL"
    QUERY = "QUERY"
    QUERY_RESULT = "QUERY_RESULT"
    JUDGE_SCORE = "JUDGE_SCORE"
    FINAL_RESULT = "FINAL_RESULT"
    PLUGIN_LOAD = "PLUGIN_LOAD"
    NODE_LOST = "NODE_LOST"
    ERROR = "ERROR"


EXP_VERSION = "1.0"
