# PyInstaller spec for ENXAME Universal Installer (Windows .exe)
# Build: pyinstaller --clean enxame_installer.spec

block_cipher = None

a = Analysis(
    ['universal_installer.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('../bees', 'bees'),
        ('../core', 'core'),
        ('../bibliotecario', 'bibliotecario'),
    ],
    hiddenimports=[
        'bees',
        'bees.config',
        'bees.service',
        'bees.librarian',
        'bees.memory',
        'bees.discovery',
        'bees.protocol',
        'bees.protocol.messages',
        'bees.protocol.handler',
        'bees.protocol.envelope',
        'bees.capabilities',
        'bees.capabilities.provider',
        'bees.capabilities.selector',
        'bees.capabilities.discovery',
        'core.ollama.client',
        'core.discovery.mdns_discovery',
        'core.exp.security',
        'core.exp.secure_logger',
        'bibliotecario.embeddings',
        'bibliotecario.indexer',
        'bibliotecario.lancedb_store',
        'bibliotecario.zim_reader',
        'bibliotecario.web_client',
        'zeroconf',
        'aiohttp',
        'httpx',
        'pydantic',
        'lancedb',
        'sentence_transformers',
        'torch',
        'numpy',
        'ollama',
        'pytesseract',
        'cryptography',
        'psutil',
        'platformdirs',
        'rich',
        'PIL',
        'fitz',
        'pdfplumber',
        'docx',
        'zimply',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'pytest', 'jupyter', 'notebook',
        'IPython', 'sphinx', 'docutils', 'setuptools', 'wheel',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='enxame_installer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='enxame.ico',  # Opcional: criar ícone
    version='version_info.txt',  # Opcional: version info
)